### ISSUE TITLE
PICO initialization fails with dummy values

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#454]
**Description**

When initializing PISM with PICO, it fails at:

`pismr: /home/albrecht/pism20/pism1.2/src/coupler/ocean/PicoPhysics.cc:178: double pism::ocean::PicoPhysics::T_star(double, double, double) const: Assertion T_s < 0.0 failed.`

for  standard values T_dummy =271.650, S_dummy=34.700.

**PISM version**

PISMR (basic evolution run mode) stable v1.2-2-g3e480b22a committed by Constantine Khrulev on 2020-02-13 13:18:02 -0900

**To Reproduce**

1. See run_withshelf_pik.py based on examples/marine in [issue_pico.tar.gz](https://github.com/pism/pism/files/4293369/issue_pico.tar.gz)
2. See circular_ice_sheet_pico.py as called in 1.

**Expected behavior**

When commenting line 178 in  src/coupler/ocean/PicoPhysics.cc, PISM runs fine.

**Additional context**

Is the `assert(T_s < 0.0);` really necessary, as it is set to` std::min(T_s, 0.0);` anyway. Why can `T_s` be negative here?

**Comment by ckhroulev** [comment]
> Is the `assert(T_s < 0.0);` really necessary <...> ?

No, I don't think so.

> Why can `T_s` be negative here?

Do you mean positive? I must have added that `assert(....)` to answer that exact question. It turns out that there is a reasonable combination of potential temperature, ocean temperature, salinity, and ice thickness that leads to `T_s` that is positive.

I removed the offending line in the code and will include this change in the next bug-fix release.

**Comment by ckhroulev** [comment]
Also: note that `assert(...)` macros have no effect in *optimized* code.

**Comment by ronjareese** [comment]
In commit 5a9cb0dc757e7905963062a28b9ec97793a5466d in which assert(T_s < 0.0) was added, also 

> return theta_pm(salinity, pressure) – temperature; 

was replaced with 

> return std::min(T_s, 0.0);

However, T_s (=theta_pm(salinity, pressure) – temperature) should be able to become positive when refreezing occurs. Setting it to 0 in this case means that ocean temperature and salinity is not affected by the refreezing. This leads to an overestimation of the refreezing.

**Comment by ckhroulev** [comment]
@ronjareese Thanks for the update.

**Comment by talbrecht** [comment]
We should not forget about changing this back in dev:
```
-  return std::min(T_s, 0.0);
+  return T_s;
```

**Comment by ckhroulev** [comment]
@talbrecht is this fixed in `dev`, now that #482 is merged?

**Comment by talbrecht** [comment]
No, it is still wrong in dev. I thought it would be good to keep it separate in this pull request, but it is only one line of code...

**Comment by ckhroulev** [comment]
@talbrecht Hmm. Are you sure? This commit (9b43b58841619a8d9628b593e9a1a7befff12304) is in dev.

**Comment by talbrecht** [comment]
@ckhroulev , sorry, you are totally right, it is correct in dev now...
